FROM python:3.11-slim

# Copy the requirements file used for dependencies
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Set the working directory to /app
WORKDIR /app

# Copy the rest of the working directory contents into the container at /app
COPY *.* /app/

EXPOSE 8000

CMD ["chainlit", "run", "app.py"]